"""product subcategory

Revision ID: 36140ced5850
Revises: 60f8fd016086
Create Date: 2026-06-24 23:15:35.531050

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36140ced5850'
down_revision: str | None = '60f8fd016086'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('subcategory', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_products_subcategory'), 'products', ['subcategory'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_subcategory'), table_name='products')
    op.drop_column('products', 'subcategory')
    # ### end Alembic commands ###
