"""init schema

Revision ID: 43a80baa85c7
Revises: 
Create Date: 2026-06-23 23:27:21.268363

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43a80baa85c7'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_categories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('RAW_MATERIAL_PURCHASE', 'OPERATING', 'PAYROLL', 'EQUIPMENT', 'OTHER', name='expensecategorytype', native_enum=False, length=50), nullable=False),
    sa.Column('is_inventory_related', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materials',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index(op.f('ix_materials_category'), 'materials', ['category'], unique=False)
    op.create_index(op.f('ix_materials_name'), 'materials', ['name'], unique=False)
    op.create_table('products',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('default_price', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_table('users',
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('super_admin', 'boss', 'warehouse_manager', 'shift_master', 'sales_manager', name='userrole', native_enum=False, length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('warehouses',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('RAW_MATERIALS', 'FINISHED_GOODS', 'MIXED', name='warehousetype', native_enum=False, length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_logs_user', 'audit_logs', ['user_id'], unique=False)
    op.create_table('clients',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('manager_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_manager_id'), 'clients', ['manager_id'], unique=False)
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=False)
    op.create_table('expenses',
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'BANK_TRANSFER', 'CARD', 'OTHER', name='paymentmethod', native_enum=False, length=50), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'CANCELLED', name='expensestatus', native_enum=False, length=50), server_default=sa.text("'DRAFT'"), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_category_id'), 'expenses', ['category_id'], unique=False)
    op.create_index('ix_expenses_expense_date', 'expenses', ['expense_date'], unique=False)
    op.create_index('ix_expenses_status', 'expenses', ['status'], unique=False)
    op.create_table('shift_reports',
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('shift_type', sa.Enum('SHIFT_1', 'SHIFT_2', name='shifttype', native_enum=False, length=50), nullable=False),
    sa.Column('master_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', name='shiftreportstatus', native_enum=False, length=50), server_default=sa.text("'DRAFT'"), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['master_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_reports_master_id'), 'shift_reports', ['master_id'], unique=False)
    op.create_index('ix_shift_reports_master_status', 'shift_reports', ['master_id', 'status'], unique=False)
    op.create_index('ix_shift_reports_shift_date', 'shift_reports', ['shift_date'], unique=False)
    op.create_table('stock_balances',
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('item_type', sa.Enum('PRODUCT', 'MATERIAL', name='itemtype', native_enum=False, length=50), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('material_id', sa.Uuid(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("(item_type = 'PRODUCT' AND product_id IS NOT NULL AND material_id IS NULL) OR (item_type = 'MATERIAL' AND material_id IS NOT NULL AND product_id IS NULL)", name='ck_stock_balances_item_xor'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'item_type', 'product_id', 'material_id', name='uq_stock_balances_item')
    )
    op.create_table('stock_movements',
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('item_type', sa.Enum('PRODUCT', 'MATERIAL', name='itemtype', native_enum=False, length=50), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('material_id', sa.Uuid(), nullable=True),
    sa.Column('movement_type', sa.Enum('PURCHASE_IN', 'PRODUCTION_IN', 'PRODUCTION_OUT', 'SALE_OUT', 'ADJUSTMENT_IN', 'ADJUSTMENT_OUT', 'DEFECT_OUT', 'RETURN_IN', name='movementtype', native_enum=False, length=50), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('source_type', sa.Enum('EXPENSE', 'SHIFT_REPORT', 'SHIPMENT', 'MANUAL_ADJUSTMENT', 'RETURN', name='sourcetype', native_enum=False, length=50), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(item_type = 'PRODUCT' AND product_id IS NOT NULL AND material_id IS NULL) OR (item_type = 'MATERIAL' AND material_id IS NOT NULL AND product_id IS NULL)", name='ck_stock_movements_item_xor'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stock_movements_created_at', 'stock_movements', ['created_at'], unique=False)
    op.create_index('ix_stock_movements_material', 'stock_movements', ['material_id'], unique=False)
    op.create_index('ix_stock_movements_product', 'stock_movements', ['product_id'], unique=False)
    op.create_index('ix_stock_movements_source', 'stock_movements', ['source_type', 'source_id'], unique=False)
    op.create_index('ix_stock_movements_type', 'stock_movements', ['movement_type'], unique=False)
    op.create_index('ix_stock_movements_wh_item', 'stock_movements', ['warehouse_id', 'item_type'], unique=False)
    op.create_table('expense_items',
    sa.Column('expense_id', sa.Uuid(), nullable=False),
    sa.Column('material_id', sa.Uuid(), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_items_expense_id'), 'expense_items', ['expense_id'], unique=False)
    op.create_table('orders',
    sa.Column('order_number', sa.String(length=100), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('manager_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'IN_PRODUCTION', 'READY_TO_SHIP', 'SHIPPED', 'CANCELLED', name='orderstatus', native_enum=False, length=50), server_default=sa.text("'NEW'"), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    op.create_index(op.f('ix_orders_client_id'), 'orders', ['client_id'], unique=False)
    op.create_index('ix_orders_deadline', 'orders', ['deadline'], unique=False)
    op.create_index(op.f('ix_orders_manager_id'), 'orders', ['manager_id'], unique=False)
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False)
    op.create_table('shift_report_materials',
    sa.Column('shift_report_id', sa.Uuid(), nullable=False),
    sa.Column('material_id', sa.Uuid(), nullable=False),
    sa.Column('quantity_used', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('waste_quantity', sa.Numeric(precision=14, scale=3), server_default=sa.text('0'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['shift_report_id'], ['shift_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_report_materials_shift_report_id'), 'shift_report_materials', ['shift_report_id'], unique=False)
    op.create_table('shift_report_outputs',
    sa.Column('shift_report_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('defect_quantity', sa.Numeric(precision=14, scale=3), server_default=sa.text('0'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['shift_report_id'], ['shift_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_report_outputs_shift_report_id'), 'shift_report_outputs', ['shift_report_id'], unique=False)
    op.create_table('shift_report_workers',
    sa.Column('shift_report_id', sa.Uuid(), nullable=False),
    sa.Column('worker_id', sa.Uuid(), nullable=False),
    sa.Column('hours_worked', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shift_report_id'], ['shift_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_report_workers_shift_report_id'), 'shift_report_workers', ['shift_report_id'], unique=False)
    op.create_table('order_items',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    op.create_table('payments',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'BANK_TRANSFER', 'CARD', 'OTHER', name='paymentmethod', native_enum=False, length=50), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_client_id'), 'payments', ['client_id'], unique=False)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_index('ix_payments_payment_date', 'payments', ['payment_date'], unique=False)
    op.create_table('shipments',
    sa.Column('shipment_number', sa.String(length=100), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('shipment_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'CANCELLED', name='shipmentstatus', native_enum=False, length=50), server_default=sa.text("'DRAFT'"), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipment_number')
    )
    op.create_index(op.f('ix_shipments_client_id'), 'shipments', ['client_id'], unique=False)
    op.create_index(op.f('ix_shipments_order_id'), 'shipments', ['order_id'], unique=False)
    op.create_index('ix_shipments_shipment_date', 'shipments', ['shipment_date'], unique=False)
    op.create_index('ix_shipments_status', 'shipments', ['status'], unique=False)
    op.create_table('shipment_items',
    sa.Column('shipment_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipment_items_shipment_id'), 'shipment_items', ['shipment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipment_items_shipment_id'), table_name='shipment_items')
    op.drop_table('shipment_items')
    op.drop_index('ix_shipments_status', table_name='shipments')
    op.drop_index('ix_shipments_shipment_date', table_name='shipments')
    op.drop_index(op.f('ix_shipments_order_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_client_id'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index('ix_payments_payment_date', table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_client_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_shift_report_workers_shift_report_id'), table_name='shift_report_workers')
    op.drop_table('shift_report_workers')
    op.drop_index(op.f('ix_shift_report_outputs_shift_report_id'), table_name='shift_report_outputs')
    op.drop_table('shift_report_outputs')
    op.drop_index(op.f('ix_shift_report_materials_shift_report_id'), table_name='shift_report_materials')
    op.drop_table('shift_report_materials')
    op.drop_index('ix_orders_status', table_name='orders')
    op.drop_index(op.f('ix_orders_manager_id'), table_name='orders')
    op.drop_index('ix_orders_deadline', table_name='orders')
    op.drop_index(op.f('ix_orders_client_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_expense_items_expense_id'), table_name='expense_items')
    op.drop_table('expense_items')
    op.drop_index('ix_stock_movements_wh_item', table_name='stock_movements')
    op.drop_index('ix_stock_movements_type', table_name='stock_movements')
    op.drop_index('ix_stock_movements_source', table_name='stock_movements')
    op.drop_index('ix_stock_movements_product', table_name='stock_movements')
    op.drop_index('ix_stock_movements_material', table_name='stock_movements')
    op.drop_index('ix_stock_movements_created_at', table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_table('stock_balances')
    op.drop_index('ix_shift_reports_shift_date', table_name='shift_reports')
    op.drop_index('ix_shift_reports_master_status', table_name='shift_reports')
    op.drop_index(op.f('ix_shift_reports_master_id'), table_name='shift_reports')
    op.drop_table('shift_reports')
    op.drop_index('ix_expenses_status', table_name='expenses')
    op.drop_index('ix_expenses_expense_date', table_name='expenses')
    op.drop_index(op.f('ix_expenses_category_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_manager_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index('ix_audit_logs_user', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_materials_name'), table_name='materials')
    op.drop_index(op.f('ix_materials_category'), table_name='materials')
    op.drop_table('materials')
    op.drop_table('expense_categories')
    # ### end Alembic commands ###
