"""product base_weight

Revision ID: 481024a2768b
Revises: b9411bc0ca90
Create Date: 2026-06-24 20:54:25.884139

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '481024a2768b'
down_revision: str | None = 'b9411bc0ca90'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('base_weight', sa.Numeric(precision=14, scale=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'base_weight')
    # ### end Alembic commands ###
